import Head from "next/head";
import Link from "next/link";
import { useEffect, useState } from "react";

export default function Home() {
  const [name, setname] = useState();

  useEffect(() => {
    fetch("http://localhost:3000/api/hello")
      .then((data) => data.json())
      .then((res) => setname(res.name));
  }, []);

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>Name: {name}</div>
      <Link href="/about">About</Link>
    </div>
  );
}
